TARGET := lab20_uart_async_rx_manager_zephyr
PLATFORM := zephyr

PROJECT_ROOT ?= $(abspath ../..)
COMMON := $(PROJECT_ROOT)/platform/$(PLATFORM)

BOARD := mps2/an385
BUILD_DIR := build

# Include common build rules
include $(COMMON)/Makefile.common









