#
# Serial
#
CONFIG_SERIAL=y
CONFIG_LAB20_CMSDK_UART_ASYNC=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=n
CONFIG_UART_USE_RUNTIME_CONFIGURE=n

#
# Application receive queue
#
CONFIG_RING_BUFFER=y

#
# UART0 is owned by this lab
#
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_LOG=n

#
# Debug-friendly build
#
CONFIG_DEBUG=y
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_ASSERT=y

#
# Runtime
#
CONFIG_MAIN_STACK_SIZE=2024
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
