TARGET := lab21_i2c_register_update_zephyr
PLATFORM := zephyr

PROJECT_ROOT ?= $(abspath ../..)
COMMON := $(PROJECT_ROOT)/platform/$(PLATFORM)

BOARD := mps2/an385
BUILD_DIR := build

# Include common build rules
include $(COMMON)/Makefile.common
