#
# I2C
#
CONFIG_I2C=y
CONFIG_I2C_SBCON=y

#
# Application receive queue
#
CONFIG_RING_BUFFER=y

#
# I2C is owned by this lab
#
CONFIG_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_LOG=n

#
# Debug-friendly build
#
CONFIG_DEBUG=y
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_ASSERT=y

#
# Runtime
#
CONFIG_MAIN_STACK_SIZE=2024
