ENTRY(Reset_Handler)

MEMORY
{
    FLASH (rx) :  ORIGIN = 0x00000000, LENGTH = 256K
    RAM   (rwx):  ORIGIN = 0x20000000, LENGTH = 64K
}

_sidata = LOADADDR(.data);

SECTIONS
{
    .text :
    {
	    KEEP(*(.isr_vector))
	    *(.text*)
	    *(.rodata*)
    } > FLASH

    .data :
    {
	    _sdata = .;
	    *(.data*)
	    _edata = .;
    } > RAM AT > FLASH

    .bss :
    {
	    _sbss = .;
	    *(.bss*)
	    *(COMMON)
	    _ebss = .;
    } > RAM
}
